update report endpoints
navikt/accessibility-reporting-tool pull request #60
Opened 2024-07-18 08:49 UTC by jas2908

2024-07-18 09:01 UTC, rannveigskjerve requested changes

2024-07-18 09:01 UTC, rannveigskjerve commented on app/src/main/kotlin/accessibility/reporting/tool/rest/ReportRoutes.kt
> +data class SuccessCriterionWithWcag(
Denne klassen trenger vi ikke

2024-07-18 12:56 UTC, jas2908 commented on app/src/main/kotlin/accessibility/reporting/tool/rest/ReportRoutes.kt
> +                    organizationUnit = null,
Jeg har laget en ny metode i OrganizationRepository.kt som jeg bruker for å legge inn organization unit

2024-07-18 13:03 UTC, jas2908 commented on app/src/main/kotlin/accessibility/reporting/tool/rest/ReportRoutes.kt
> +            try {
try-catch fjernet

2024-07-18 13:05 UTC, jas2908 commented on app/src/main/kotlin/accessibility/reporting/tool/rest/ReportRoutes.kt
> +data class SuccessCriterionWithWcag(
fjernet fun List<ReportShortSummary>.toReportWithUrl()

2024-07-19 08:10 UTC, rannveigskjerve approved these changes
Bra jobba!

2024-07-19 08:12 UTC, merged